model: Res16UNet34D
conv1_kernel_size: 3
weights: None
weights_for_inner_model: false
dilations:
- 1
- 1
- 1
- 1
resolution_evaluation: pred_up
child_classifier_dimension: 30
wrapper_type: None
wrapper_region_type: 1
wrapper_kernel_size: 3
wrapper_lr: 0.1
meanfield_iterations: 10
crf_spatial_sigma: 1
crf_chromatic_sigma: 12
optimizer: SGD
lr: 0.05
separate_lrs:
- 0.05
- 0.05
- 0.05
- 0.05
sgd_momentum: 0.9
sgd_dampening: 0.1
adam_beta1: 0.9
adam_beta2: 0.999
weight_decay: 0.0001
param_histogram_freq: 100
save_param_histogram: false
iter_size: 1
bn_momentum: 0.02
parent_bce_weights:
- 1.0
- 1.0
supercat_bce_weights:
- 1.0
- 1.0
classifier_only: false
loss_type: neural_collapse
focal_alpha: 1.0
scheduler: MultiStepLR
max_iter: 10000000.0
max_epoch: 400
step_size: 20000.0
multi_step_milestones:
- 120
- 150
step_gamma: 0.3
poly_power: 0.9
exp_gamma: 0.95
exp_step_size: 445
scheadule_monitor: val_miou
scheduler_min_lr: 0.001
reduce_patience: 20
log_dir: /home/studenten/User/Diyor/output/Scannet200Voxelization5cmDataset/Res16UNet34D-neural_collapse2
data_dir: data
child_label_mapper: child_classifier_mapping_30_ids.pkl
category_weights: feature_data/scannet200_category_weights.pkl
category_frequencies_path: feature_data/dataset_frequencies.pkl
weighted_cross_entropy: false
instance_sampling_weights: feature_data/tail_split_inst_sampling_weights.pkl
sample_tail_instances: false
bounding_boxes_path: feature_data/full_train_bbs_with_rels.pkl
correct_samples_prop_path: feature_data/prop_of_points_to_sample.pkl
max_instance_placing_iterations: 50
num_instances_to_add: 5
sampled_features: false
mean_features_path: feature_data/Res16UNet34C200_mean_features.pkl
spatial_distances_path: spatial_graph_distances.npy
language_features_path: feature_data/clip_feats_scannet_200.pkl
use_embedding_loss: null
embedding_loss_type: contrast
num_pos_samples: 1
num_negative_samples: 3
clip_uniform_sampling: true
contrast_pos_thresh: 0.0
contrast_neg_thresh: 0.6
contrast_neg_weight: 1.0
embedding_loss_lambda: 1.0
representation_distance_type: cos
normalize_features: false
feat_norm_loss_max: 0.2
learned_projection: false
dataset: Scannet200Voxelization5cmDataset
temporal_dilation: 30
temporal_numseq: 3
point_lim: -1
pre_point_lim: -1
batch_size: 4
val_batch_size: 4
test_batch_size: 1
effective_batch_size: 8
cache_data: false
num_workers: 4
num_val_workers: 4
ignore_label: -1
return_transformation: false
ignore_duplicate_class: false
partial_crop: 0.0
train_limit_numpoints: 1800000
scannet_path: /home/studenten/User/Diyor/scannet_preprocessed_Language/train
is_train: true
stat_freq: 100
test_stat_freq: 100
visualize_freq: 0
save_freq: 1000
val_freq: 400
empty_cache_freq: 4
train_phase: train
val_phase: val
overwrite_weights: true
resume: null
resume_optimizer: true
eval_upsample: false
lenient_weight_loading: true
train_augmentation: true
elastic_distortion: true
use_feat_aug: true
data_aug_color_trans_ratio: 0.1
data_aug_color_jitter_std: 0.05
data_aug_color_scaling_factor: 1.0
normalize_color: true
data_aug_scale_min: 0.9
data_aug_scale_max: 1.1
data_aug_hue_max: 0.5
data_aug_saturation_max: 0.2
data_aug_patch_dropout_ratio: 0.35
instance_augmentation: null
instance_augmentation_color_aug_prob: 0.5
instance_augmentation_scale_aug_prob: 0.2
projection_model_path: feature_data/scannet200_attribute_projection_model.ckpt
visualize: false
test_temporal_average: false
visualize_path: /home/studenten/User/Diyor/output/Scannet200Voxelization5cmDataset/Res16UNet34D-neural_collapse2/visualize
save_prediction: false
save_pred_dir: outputs/pred
test_phase: test
evaluate_original_pointcloud: false
test_original_pointcloud: false
gt_type: none
gt_types: []
eval_only_on_parents: true
overfit_batches: 0.0
is_cuda: true
load_path: ''
log_step: 50
log_level: INFO
num_gpu: 1
seed: 42
balanced_category_sampling: true
balanced_sample_head_ratio: -1
balanced_sample_common_ratio: -1
wandb_id: 57a2ghbey2
